### ISSUE TITLE
What does calysto_chatbot do?

### ISSUE THREAD

**Issue by nealmcb** [Calysto/calysto_chatbot#1]
I can interpret the current description of calysto_chatbot in the README.md in various different ways, but none really make sense to me yet.  It sounds fun, but what does it do?

Does it provide me a user interface to my favorite chat protocols, so I can talk about a notebook with others during a teleconference where I'm presenting the notebook?

Does it let me write python scripts to make a bot to automatically post chat messages on various chat networks?

Does it chat with me about the software and presentations I'm developing?

How does it integrate with the notebook or the console?

What chat protocols does it support?

Any screenshots?

Or am I completely off base?

Thanks!

**Comment by dsblank** [comment]
You're not off base :) Chatbot is a work in progress. Currently, if you install it from gtihub (say, using pip) and ipython3, then it should install everything you need to start a kernel that is an AIML chatbot.

What I would like it to become is a way for users (really students in my case) to create and test chatbots interactively. I think we just added a %load magic, but when I get a few free cycles, I'll try to document it more, and add a but of code to allow adding/changing the AIML "rules" on the fly.

But please feel free to install, test, and contribute!

**Comment by dsblank** [comment]
Here is a link to the main resource on AIML: http://www.alicebot.org/aiml.html

**Comment by nealmcb** [comment]
Ahh - I was looking for ipython extensions that would help me with my python development.

But I guess you're saying that this is more like an AIML / ALICEBOT integration to let folks use Jupyter as a development environment for bots. (?)  Cool!

I'm still getting used to the idea of Jupyter allowing such diversity in kernels, which might have nothing to do with python....

Describing a use case in the README, and giving a sample dialog with the kernel would help a lot :)

Thanks again.

**Comment by alfnitacoder** [comment]
Please help i just downloaded and installed what next how to test yes cool!! i can see aimlbotkernel. but how to write a new one 
should i write like this?
import aimlbotkernel
l=aimlbotkernel.kernel()
l.aimlbot("aiml.xml")

**Comment by dsblank** [comment]
Hi! This is really just a demo at this point... you can only converse with the chatbot. It would be cool to edit this so that one could do development with it too.

**Comment by alfnitacoder** [comment]
thanks @dsblank that was quick :) can you point me to the right track how to do it.

**Comment by dsblank** [comment]
Well, that is a tough question... you'd need to decide what you want to happen when you enter text into a cell: is it a conversation, or is it Python code? You could make it toggle between two modes by using a magic. For example, it might start out in conversation mode, but after a `%config mode development` or something it switches into Python mode. The code to handle the switched modes would be here:

https://github.com/Calysto/calysto_chatbot/blob/master/calysto_chatbot/kernel.py#L43

I see that there is already one such command there: `%learn` for loading additional files. Maybe that is all you need?

**Comment by alfnitacoder** [comment]
ipython3 console --kernel calysto_chatbot
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 445, in initialize_subcommand
    subapp = import_item(subapp)
  File "/usr/lib/python3/dist-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named 'jupyter_console'

**Comment by dsblank** [comment]
To run with newer jupyter, you will need to "pip install jupyter_console" and maybe other components.

**Comment by alfnitacoder** [comment]
@dsblank seems working now

ipython console calysto_chatbot
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
Jupyter console 5.0.0

Python 2.7.13 (default, Dec 18 2016, 20:19:42) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.



In [1]
i thought it will load aiml and properties after running that command. now that i have it running can you tell what is the next step

**Comment by dsblank** [comment]
Updates:

Use "load NAME" to load collection of rules. Example:

```
load alice
```

Use:

```
%learn {AIML_PATH}/standard/startup.xml
load aiml b
```
